{% set name = "couchdb" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/couchdb/source/{{ version }}/apache-couchdb-{{ version }}.tar.gz
  sha256: d27ff2a13356000296a98ab884caf3d175927cf21727963ff90fab3a747544cf
  patches:
    - fixup_spidermonkey_search.patch

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}    # [unix]
    - {{ stdlib('c') }}      # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - make                   # [unix]
  host:
    - erlang        # [unix]
    - openssl       # [unix]
    - icu           # [unix]
    - zlib          # [unix]
    - ncurses       # [unix]
    - spidermonkey  # [unix]

test:
  commands:
    - couchjs -V

about:
  home: https://couchdb.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: |
    Seamless multi-master sync, that
    scales from Big Data to Mobile,
    with an Intuitive HTTP/JSON API
    and designed for Reliability.
  description: |
    Apache CouchDB™ lets you access your data where you need it. The Couch Replication Protocol is implemented in a variety of projects and products that span every imaginable computing environment from globally distributed server-clusters, over mobile phones to web browsers.

    Store your data safely, on your own servers, or with any leading cloud provider. Your web- and native applications love CouchDB, because it speaks JSON natively and supports binary data for all your data storage needs.

    The Couch Replication Protocol lets your data flow seamlessly between server clusters to mobile phones and web browsers, enabling a compelling offline-first user-experience while maintaining high performance and strong reliability. CouchDB comes with a developer-friendly query language, and optionally MapReduce for simple, efficient, and comprehensive data retrieval. 
  doc_url: https://docs.couchdb.org/en/stable/
  dev_url: https://github.com/apache/couchdb

extra:
  recipe-maintainers:
    - pepijndevos
